language: python
python:
  - "3.6"
  - "nightly"
install:
  - pip install -q -r pip-req.d/install.txt -r pip-req.d/test.txt
script:
  - python -m unittest discover -v tests/ 'test_*.py'
  - flake8 .
  - isort --check-only --recursive .
matrix:
  allow_failures:
    - python: nightly
